
---
spring:
  profiles: cloud
  cloud:
    config:
      server:
        git:
          uri: https://github.com/twinkle-cloud/ServiceConfig.git
          #If you need to build your own config server, please use your account & password
          username: SaasAdmin
          password: 5MCqizxdKkA-UTiMRZxC
          default-label: master

info:
  description: Config Server for twinkle Cloud project
  url: https://github.com/twinkle-cloud/ServiceConfig.git

---
spring:
  profiles: development
  cloud:
    config:
      server:
        git:
          uri: http://githup.com/cxj110/twinkle-cloud/config/development.git
           #If you need to build your own config server, please use your account & password
          username: SaasAdmin
          password: 5MCqizxdKkA-UTiMRZxC
        health:
          repositories:
            discovery:
              label: master
              profiles: cloud

---
spring:
  profiles: test
  cloud:
    config:
      server:
        git:
          uri: http://githup.com/cxj110/twinkle-cloud/config/development.git
          #If you need to build your own config server, please use your account & password
          username: SaasAdmin
          password: 5MCqizxdKkA-UTiMRZxC
        health:
          repositories:
            discovery:
              label: master
              profiles: cloud



