
server:
  port: 9021
logging:
  path: /Users/chenxj/Documents/Temp/
  
ribbon:
  eureka:
    enabled: true


---
spring:
  profiles: cloud
  jpa:
    show-sql: false
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://192.168.1.252:3307/foxbase?useUnicode=true&amp;characterEncoding=utf8
    username: vaadin
    password: abcd1234
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  data:
    rest:
      default-page-size: 1000
    
---
spring:
  profiles: development
  jpa:
    show-sql: false
    database: MYSQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://61.178.80.86:3306/yy?useUnicode=true&amp;characterEncoding=utf8
    username: admin
    password: 1qaz!QAZ
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  data:
    rest:
      default-page-size: 1000


---
spring:
  profiles: test
  jpa:
    show-sql: false
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://15.114.102.7:3306/foxtest?useUnicode=true&amp;characterEncoding=utf8
    username: admin
    password: 1qaz!QAZ
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  redis:
    database: 11
    host: 15.114.102.10
    port: 6379
    pool:
      max-active: 10
      max-idle: 10
      max-wait: -1
      min-idle: 0
  data:
    rest:
      default-page-size: 1000

    
---
spring:
  profiles: local
  jpa:
    show-sql: false
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/yy-base?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  redis:
    database: 6
    host: 15.114.102.10
    port: 6379
    pool:
      max-active: 10
      max-idle: 10
      max-wait: -1
      min-idle: 0
  data:
    rest:
      default-page-size: 1000

    