spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:1qaz\!QAZ}
    lettuce:
      pool:
        max-active: 300
        max-idle: 8
        max-wait: -1
    #timeout: 5000
  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  #jwt密码
  security:
    oauth2:
      jwt:
        signingKey: 123456
  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 2  #流速 每秒
            redis-rate-limiter.burstCapacity: 10   #令牌桶的容积
            rate-limiter: "#{@defaultRedisRateLimiter}"  #SPEL表达式去的对应的bean
            key-resolver: "#{@apiKeyResolver}" #SPEL表达式去的对应的bean

twinkle:
  bus:
    receiver:
      exchange-name: spring-boot-exchange
      routing-key: gateway-route
      enable: true
  security:
    ignored: /oauth/**,/open/**,/v2/api-docs/**, /noauth/**, /swagger**,/swagger**/**,/webjars/**,/v2/**, /js/**, /css/**


feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true

jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  hidePackages: com.twinkle.cloud
  local:
    # 默认永久本地缓存
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    # 默认永久的远程缓存
    default:
      type: redis.springdata
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo

#网关白名单，无需要签权url
gate:
  ignore:
    authentication:
      startWith: /*/noauth,/noauth,/oauth,/open,/v2/api-docs

management:
  endpoints:
    web:
      exposure:
        include: '*'
